CREATE DATABASE Customer_Behaviour
USE Customer_Behaviour


select * from customer limit 20

# Q1) What is the tottal revenue generated by male vs female customers?
select gender, sum(purchase_amount) as revenue
from customer
group by gender

# Q2) Which customers used discount and still spent more than the avergae purchase amount
select customer_id, purchase_amount
from customer
where discount_applied = 'Yes' and purchase_amount >= (select Avg(purchase_amount) from customer)

# Q3) Which are the top 5 produts with the heighest avergae review rating?
select item_purchased, round(Avg(review_rating),2) as 'Average Product Rating'
from customer
group by item_purchased
order by avg(review_rating) desc
limit 5

# Q4) Compare the average purchase amounts between standard and express shipping
select shipping_type, avg(purchase_amount) as 'Most purchased'
from customer
where shipping_type in ('Standard','Express')
group by shipping_type

# Q5) Do describe customers spend more? Compare average spend and total revenue between subs and non subs
select subscription_status, count(customer_id) as total_customers, round(avg(purchase_amount),2) as avg_spend,
round(sum(purchase_amount),2) as total_revenue
from customer
group by subscription_status
order by total_revenue, avg_spend desc;

# Q6) Which 5 products have the heighst percentage of purchases with discounts applied
select item_purchased, round(100 * sum(case when discount_applied = 'Yes' then 1 else 0 end)/ count(*),2) as discount_rate
from customer
group by item_purchased
order by discount_rate desc
limit 5

# Q7) Segment customers into new, returning and loyal based on their total numbe f previous purchases, and show the count of each segment
with customer_type as (
select customer_id, previous_purchases,
case
	when previous_purchases = 1 then 'New'
    when previous_purchases between 2 and 10 then 'Returning'
    else 'Loyal'
    end as customer_segment
from customer
)
select customer_segment, count(*) as 'Number of Customers'
from customer_type
group by customer_segment

# Q8) What are the top 3 most purchased products within each categoey?
with item_counts as (
select category, item_purchased, count(customer_id) as total_orders,
row_number()over(partition by category order by count(customer_id) desc) as item_rank
from customer
group by category, item_purchased
)
select item_rank, category, item_purchased, total_orders
from item_counts
where item_rank <=3

# Q9) Are customers who are repeat buyers(more than 5 previous purchases) also likely to subscribe?
select subscription_status,
count(customer_id) as repeat_buyers
from customer
where previous_purchases > 5
group by subscription_status

# Q10) What is the revenue contribution of each age group?
select age_group,
sum(purchase_amount) as total_revenue
from customer
group by age_group
order by total_revenue desc